#!/usr/bin/env node
// Serialises gated essays to JSON for the private directory, and writes the
// manifest of gated slugs the client uses to know which essays to request
// from the server rather than expect in the bundle.
//
// This is what makes the paywall real. Essays under src/data/articles/ are
// bundled by Vite and world-readable; essays under src/data/articles/gated/
// are never imported by the client at all — they end up in dist/tl-essays/,
// which the deploy places ABOVE the document root where Apache cannot serve
// them. api/essay.php is the only way to read them.
//
// Runs before `vite build`. Also run by the test harness.

import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(here, '..');
const gatedDir = path.join(webRoot, 'src/data/articles/gated');
const outDir = path.resolve(webRoot, '../../dist/tl-essays');
const manifest = path.join(webRoot, 'src/data/gatedSlugs.generated.js');

const { articles } = await import(path.join(webRoot, 'src/data/articles.js'));
const bySlug = new Map(articles.map((a) => [a.slug, a]));

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const files = readdirSync(gatedDir).filter((f) => f.endsWith('.js'));
const slugs = [];
let bytes = 0;

for (const file of files) {
    const slug = file.replace(/\.js$/, '');
    const meta = bySlug.get(slug);
    if (!meta) {
        throw new Error(`gated/${file} has no matching record in articles.js — the slug must exist in the index or the essay is unreachable`);
    }

    const mod = await import(path.join(gatedDir, file));
    const record = {
        slug,
        // Drafts are owner-preview-only; the rest are members-only. essay.php
        // needs to know which, because they get different status codes.
        comingSoon: Boolean(meta.comingSoon),
        content: mod.default || {},
    };

    const json = JSON.stringify(record);
    writeFileSync(path.join(outDir, `${slug}.json`), json, 'utf8');
    bytes += Buffer.byteLength(json);
    slugs.push(slug);
}

slugs.sort();

writeFileSync(
    manifest,
    '// GENERATED by tools/split-essays.mjs — do not edit.\n' +
    '// Slugs whose text lives on the server, not in this bundle. The client\n' +
    '// uses this only to know it must ask api/essay.php; it grants nothing.\n' +
    `export const gatedSlugs = new Set(${JSON.stringify(slugs, null, 4)});\n`,
    'utf8'
);

console.log(`essays: ${slugs.length} gated -> dist/tl-essays (${Math.round(bytes / 1024)}KB), ${bySlug.size - slugs.length} free stay in the bundle`);
